#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  echo "Usage: chmod++ <file extension>"
  echo "E.g. chmod++ .sh"
  echo "E.g. chmod++ '*'"
  echo "E.g. chmod++ a"
  echo "^The last two will take all files in the pwd as the argument^"
  exit 1
fi

# Strict error handling i guess idk
set -euo pipefail

if [[ "$1" =~ ^([a|*]) ]]; then
  file_type_warn="every file"
else
  file_type_warn="every $1 file"
fi

# warning
echo -e "\033[1;31mWarning:\033[0m"
echo "Are you sure you want to make $file_type_warn in the CURRENT directory executable? (Y/N)"
read -r opti

# confirmation
if [[ "$opti" =~ ^([yY]|yes|YES)$ ]]; then

shopt -s nullglob
  
if [[ "$1" =~ ^([a|*]) ]]; then
  files=(*)
else
  files=($1)
fi 

shopt -u nullglob

  if [ ${#files[@]} -eq 0 ]; then
    echo "No files matching the pattern '$1' found in the current directory."
    exit 0
  fi


  echo "Making the following files executable:"
  printf '%s\n' "${files[@]}"

  chmod +x -- "${files[@]}"
  echo "Done."
else
  echo "Chmod++ cancelled. Bye-bye."
fi
